# src/main/resources/application-prod.yml
spring:
  config:
    import: optional:dotenv:.
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

app:
  web:
    public-base-path: /sb/deokhugam

  external:
    naver:
      base-url: https://openapi.naver.com/v1/search
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      download-thumbnail: true

    ocr:
      base-url: https://api.ocr.space
      api-key: ${OCR_SPACE_API_KEY}
      ocr-engine: 2
      language: kor

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: OFF
